export * from './ping.controller';
export * from './jurados-area-investigacion.controller';
export * from './jurados-evaluacion-solicitud.controller';
export * from './evaluacion-solicitud-resultado-evaluacion.controller';
export * from './evaluacion-solicitud.controller';
export * from './resultado-evaluacion.controller';
export * from './usuario.controller';
export * from './roles.controller';
export * from './usuario-roles.controller';
